### ISSUE TITLE
Issues with stacking

### ISSUE THREAD

**Issue by katubug** [kwpugh/mob_catcher_fabric#1]
I am sorry for how bad this report will be, I'm on my phone. I am using the second to latest version of the mod, and the mob catchers stack. However, when you right click a stack of them on a mob, it doesn't split the stack. So it treats the stack as if it was one item, holding whatever mob you clicked. I haven't been able to test whether this duplicates the mob.

I can provide more information if needed - which I assume will be the case, sorry about that - just let me know!

**Comment by kwpugh** [comment]
Oh, that is bad, but it is an easy fix.  Thank you for reporting.  Should have a fix out shortly.

**Comment by katubug** [comment]
Thank you so much! And I'm happy to help 💗 I love your mods.

**Comment by kwpugh** [comment]
I just published v1.0.10 with the fix. And thank you for using my mods in your modpack, enjoy.
