### ISSUE TITLE
[1.18.2/1.19] Cant pick up dolphins or fish

### ISSUE THREAD

**Issue by keepinitreal247** [kwpugh/mob_catcher_fabric#10]
So uh I just can't pick dolphins or fish up when in the water I just end up hitting them 😭😭😭 there no crash or anything it's a good mod this is the only issue I'm having I'm using the diamond one

**Comment by kwpugh** [comment]
Fish do work, their hotbox is just a bit tricky

I  will add  dolphins  next update.

**Comment by kwpugh** [comment]
oh, are  you using  the  forge version?  Looks  like I forgot to put those in that version.

**Comment by kwpugh** [comment]
Just published new versions for forge and fabric 1.18.2

**Comment by kwpugh** [comment]
published new versions for  forge and fabric 1.19.0
