### ISSUE TITLE
Health stacking when paired with RPG difficulty, Fabric 1.19.2

### ISSUE THREAD

**Issue by AnomalousDeity** [kwpugh/mob_catcher_fabric#14]
When using the hostile mob Catcher upon catching and releasing, the hostiles health grows and grows to be over a thousands of hearts on each release. the mod is also Up to date

**Comment by kwpugh** [comment]
Which mobs?

**Comment by AnomalousDeity** [comment]
like skeletons, creepers, originally it affected passive mobs but after updating to latest version thats not the case, but so far hostile mobs still health stack

**Comment by kwpugh** [comment]
seems like the same issue with another mod that lets you capture an entity
https://github.com/Globox1997/RpgDifficulty/issues/62

**Comment by kwpugh** [comment]
I tested with rpgdifficulty-1.3.12+1.19.2 and the issue did not occur for me.  Perhaps it is fixed now.

**Comment by kwpugh** [comment]
Unable to replicate, closing
