### ISSUE TITLE
Mob Capture Durability

### ISSUE THREAD

**Issue by SliMHaZe** [kwpugh/mob_catcher_fabric#16]
This isn't and Issue but a suggestion for Mob Capture, My friend and Me (We are on a Team) are having trouble finding a way to make durability for the Mob Catchers. We tried to do it by scratch and everything, but to no avail... I would love for their to be less of an ease with this mod, I want players to think strategically about what they capture so that there is still a challenge when it comes to the Transports of mobs.

**Comment by markygnlg** [comment]
Great idea!

A cheap recipe for a single use & an expensive recipe for re-use maybe?

Also, maybe config options to set how many re-uses for cheap & expensive catchers?

**Comment by Chris-Creates** [comment]
i was hoping this was a thing already lol

**Comment by kwpugh** [comment]
After thinking this through I have decided that I do not want to add durability to the catchers.  Thank you for the suggestions though.
