### ISSUE TITLE
Suggestion [x2] Stackable & Erase NBT data when empty

### ISSUE THREAD

**Issue by markygnlg** [kwpugh/mob_catcher_fabric#17]
- Stackable?
 - Could you erase the NBT data when I release a mob? I use an auto-inventory-sorter which groups the mob-catchers based on the currently used & the left over NBT data (ie. last mob that was released NBT & the current 'used/full' NBT data).
  It makes it hard to find empty mob-catchers (I need to wait for the 'twinkling' colors in order to see which mob-catchers are 'in use/full' vs empty).

Thanks for this great mod too!

**Comment by kwpugh** [comment]
With the transition away from NBT and the advent of DataComponents in 1.20.5, I don't think this really applies anymore.
