### ISSUE TITLE
Config is not generating/working on Forge, works fine on Fabric. 

### ISSUE THREAD

**Issue by purejosh** [kwpugh/mob_catcher_fabric#19]
A couple users in the discord had an issue with the config on Forge, so I tested it for them. The config isn't generating, and it also won't pull info from an existing config. I've also tried the datapack without any config changes, and that's not working. 
![image](https://github.com/kwpugh/mob_catcher_fabric/assets/70633949/4cbf2971-3915-46f5-9dec-b9a202da59e9)

**Comment by kwpugh** [comment]
The forge version does not have a config or any data pack features, only the fabric version does
