### ISSUE TITLE
Mod not showing up

### ISSUE THREAD

**Issue by annam12345** [kwpugh/mob_catcher_fabric#2]
For some reason I cant get the mod to show up in the game. I've downloaded it, made sure its the correct version and file type and put it in the mod folder but when looking at the mods in game, its not showing up and no matter what I try, I cant get the mob catcher to actually show up. Not sure if theres a problem on my end, if I need to do something or if it's with the mod itself.

**Comment by kwpugh** [comment]
Post a  copy of your  latest log.  Dumb question,  but did you install Fabric as well?

**Comment by kwpugh** [comment]
no  further info, closing.
