### ISSUE TITLE
Parity sync between Fabric and Forge

### ISSUE THREAD

**Issue by purejosh** [kwpugh/mob_catcher_fabric#20]
In the Fabric version, you right click to capture and right click to release. Also, it's named passive/hostile catcher. 
In the Forge version, you left click to capture and right click to release, and the items are named diamond/netherite. 

For the sake of simplicity, could you sync these two mods so they have identical verbiage, actions, etc?

**Comment by kwpugh** [comment]
on the list.

**Comment by kwpugh** [comment]
This is addressed in 1.20.6+
