### ISSUE TITLE
Problem with compat with Genetic animals - 1.18.2

### ISSUE THREAD

**Issue by chrichriGeorgie** [kwpugh/mob_catcher_fabric#21]
It happened randomly 2 times (1 cow and 1 chicken) but when I catched them with the diamond mob catcher, their gene are reinitialized to defaults. The two mob that changed where spawned when de world loaded.

It was in creative with minecraft 1.18.2 Forge (MobCatcher-Forge-1.18.2-1.1.6.jar + GeneticAnimals-0_8_25.jar). I was playing in a LAN server (I was not the host)

I wish I had more details on how it happened but except those two random times, I was not able to reproduce the issue with mobs I spawned with the egg.

**Comment by chrichriGeorgie** [comment]
[latest.zip](https://github.com/kwpugh/mob_catcher_fabric/files/12235358/latest.zip)

Here is the log, I checked it quickly, but I did not find interesting info

**Comment by kwpugh** [comment]
The catcher simply creates a new mob of the type, so and modifications to the mob are lost.

**Comment by kwpugh** [comment]
I will not be pursuing this enhancement
