### ISSUE TITLE
Suggestion: add entity type blacklist tag for this mod

### ISSUE THREAD

**Issue by TelepathicGrunt** [kwpugh/mob_catcher_fabric#22]
Hello, I am making some new entities for my mod and was looking into various mod's abilities to capture my entities. Most are using a tag blacklist so I am able to add my entity to those tags by adding the tag to my jar file. Mob Catcher seems to not have a blacklist tag which means I can't prevent the item from capturing my new uncapturable entities by default. Would you be willing to add a tag for this?

**Comment by kwpugh** [comment]
When I get back to updating mods, I will do that

**Comment by kwpugh** [comment]
I'm finally getting around to these, sorry for the delay.

At this point, should I just be checking that the entity in question is NOT in `CAPTURING_NOT_SUPPORTED` ?

**Comment by kwpugh** [comment]
this seems to work on a test entity

`              EntityType<?> entityType = entity.getType();
                boolean disallowed = entityType.isIn(ConventionalEntityTypeTags.CAPTURING_NOT_SUPPORTED);
                if(disallowed) return;`

**Comment by kwpugh** [comment]
ok, I think I figured out how to use the new tag

**Comment by kwpugh** [comment]
I will also add the check to my Staff of Ensnarements in Gobber.

**Comment by kwpugh** [comment]
Which version of Minecraft did you add the new mob in question?  I fixed this for 1.20.6 and I'm wondering how far back I may need to back port.

**Comment by TelepathicGrunt** [comment]
My Bumblezone mod with the entity in question is on 1.20.1 and 1.20.4 as my main supporting versions for a while
