### ISSUE TITLE
it doesn't work when I launch Minecraft.

### ISSUE THREAD

**Issue by 1Kop** [kwpugh/mob_catcher_fabric#3]
I download the mod and fabric and fabric API and put it in mods folder when I attempt to launch Minecraft I get this error.
![Screenshot 2021-11-19 214633](https://user-images.githubusercontent.com/89232485/142711939-b93759d8-d49a-427f-a867-d3c7bab94d04.png)
Can someone tell me how to fix.

**Comment by kwpugh** [comment]
as it says in the errors message, you need to install Cloth Config mod

**Comment by 1Kop** [comment]
> as it says in the errors message, you need to install Cloth Config mod

tysm. it works now.

**Comment by kwpugh** [comment]
great.  enjoy.
