### ISSUE TITLE
[1.18.1] The Forge beta version has Cloth Config Fabric as a dependency

### ISSUE THREAD

**Issue by brisingraerowing** [kwpugh/mob_catcher_fabric#6]
This makes the CF app install it along with this mod, though removing it doesn't remove this mod (likely due to a bug in the last 3? 4? releases of the CF app). I'm presuming that should reference the Forge version of Cloth Config.

**Comment by kwpugh** [comment]
Actually, Cloth Config should not be required, I'll fix that.

**Comment by kwpugh** [comment]
Since the mobs are on the same project (for now), they share a single common dependency.  This will go away when Mob Catcher gets its own project.

**Comment by kwpugh** [comment]
Mob Catcher for Forge is not a thing anymore.
