### ISSUE TITLE
Cloth config bug back in Forge 1.18.2

### ISSUE THREAD

**Issue by Raidobw2** [kwpugh/mob_catcher_fabric#7]
Thank you for updating the mod for Forge, I will be able to use this! It looks like the Forge version, when downloaded on the CurseForge App, drags the Fabric dependency of Cloth Config into the mods folder. This is the same as #6, but for 1.18.2. Not really a bug, just a small thing to adjust in the workflow probably.

Thank you in advance

**Comment by kwpugh** [comment]
That  is because  curse  doesn't support forge/fabric together and dependency issue for the whole project.  Folks will need to download manually  to avoid getting Cloth or just remove it if it gets downloaded.

**Comment by Raidobw2** [comment]
Ah I see, thank you for the info. I'll assume modpacks that pull from CurseForge will work fine then, to my understanding they should be able to pull the single file and the Forge dependency both as standalones. If I get problems I'll make sure to let you know here, thank you!
