### ISSUE TITLE
[1.18.2] Game crashes on mods screen from main menu in the Forge version

### ISSUE THREAD

**Issue by Raidobw2** [kwpugh/mob_catcher_fabric#9]
In mods screen from main menu if you click mob catcher mod then game crashes

Steps to reproduce:
1. Go to mods from main menu
2. Click mob catcher

Logs
https://paste.feed-the-beast.com/view/ce8c321f

Happens on version 1.1.0, 1.1.1. For Forge, in Minecraft 1.18.2

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/956

**Comment by kwpugh** [comment]
Fixed in next update 1.1.2

**Comment by Raidobw2** [comment]
Thank you!
